#!/usr/bin/env bash
set -eo pipefail

# Default remote hope root. You can override:
#   HOPE_ROOT=/path/to/GenRec/hope bash init_grec_cb_hope_dirs.sh
HOPE_ROOT="${HOPE_ROOT:-/mnt/dolphinfs/hdd_pool/docker/user/hadoop-hmart-poistar/fanghaotian/GenRec/hope}"

DIR_NAMES=(
  "Qwen2_5-3B-Instruct-qwen4B-4-32-MIMIGenRec-grec"
  "Qwen2_5-3B-Instruct-qwen4B-4-64-MIMIGenRec-grec"
  "Qwen2_5-3B-Instruct-qwen4B-4-128-MIMIGenRec-grec"
  "Qwen2_5-3B-Instruct-qwen4B-4-512-MIMIGenRec-grec"
)

if ! command -v hope >/dev/null 2>&1; then
  echo "[ERROR] 'hope' command not found in PATH."
  exit 1
fi

mkdir -p "${HOPE_ROOT}"

for dir_name in "${DIR_NAMES[@]}"; do
  dir_path="${HOPE_ROOT}/${dir_name}"
  mkdir -p "${dir_path}"

  (
    cd "${dir_path}"
    # .hope file is generated by hope init; skip if already exists.
    if [[ ! -f "${dir_name}.hope" ]]; then
      hope init ml-easy-job "${dir_name}"
    else
      echo "[INFO] Skip hope init, exists: ${dir_path}/${dir_name}.hope"
    fi
  )

  touch \
    "${dir_path}/${dir_name}.sh" \
    "${dir_path}/${dir_name}-rl.sh" \
    "${dir_path}/${dir_name}-evaluate.sh"

  chmod +x \
    "${dir_path}/${dir_name}.sh" \
    "${dir_path}/${dir_name}-rl.sh" \
    "${dir_path}/${dir_name}-evaluate.sh"

  echo "[INFO] Prepared: ${dir_path}"
done

echo "[INFO] Done."
