#!/bin/bash
set -eo pipefail

DEFAULT_GREC_ROOT="/mnt/dolphinfs/hdd_pool/docker/user/hadoop-hmart-poistar/fanghaotian/GenRec"
: "${GREC_ROOT:=$DEFAULT_GREC_ROOT}"

if [[ ! -d "$GREC_ROOT" ]]; then
  echo "Error: GREC_ROOT does not exist: $GREC_ROOT" >&2
  exit 1
fi

cd "$GREC_ROOT" || exit 1

# IAG: Instruments + Arts + Games
: "${ROOT_DIR:=/mnt/dolphinfs/hdd_pool/docker/user/hadoop-hmart-poistar/fanghaotian}"
: "${DATA_ROOT:=${ROOT_DIR}/data}"
: "${MODEL_NAME:=qwen3-embedding-4B}"
: "${USE_MULTI_DATASETS:=true}"
: "${DATASETS:=Instruments Arts Games}"

# Required: checkpoint generated by index training.
: "${CKPT_PATH:=/mnt/dolphinfs/hdd_pool/docker/user/hadoop-hmart-poistar/fanghaotian/GenRec/index_train_runs/Instruments-Arts-Games/index/qwen3-embedding-4B/rq4_cb256-256-256-256_sk0.0-0.0-0.0-0.003_kmtrue-lkmtrue-kmi100/run_time/best_collision_model.pth}"
if [[ -z "$CKPT_PATH" ]]; then
  echo "Error: CKPT_PATH is empty."
  echo "Example: CKPT_PATH=./index_train_runs/Instruments-Arts-Games/index/qwen3-embedding-4B/run_tag/run_time/best_collision_model.pth bash scripts/index/Instruments-Arts-Games-qwen3-embedding-4B-rq4_cb256-256-256-256_sk0.0-0.0-0.0-0.003/generate.sh"
  exit 1
fi

export ROOT_DIR DATA_ROOT MODEL_NAME USE_MULTI_DATASETS DATASETS CKPT_PATH

# Optional overrides (examples):
#   BATCH_SIZE=64 DEVICE=cuda:0 OUTPUT_SUFFIX=.index_custom.json
bash "$GREC_ROOT/scripts/index/base/generate.sh"
